version: "3.3"

services:
  db:
    image: mongo:4.4
    container_name: "atsGo_container"
    networks:
      - atsGo
    ports:
      - 27017:27017

  atsGo:
    image: atsgo:1.1.3
    build: .
    environment:
      - ATSGO_DB_ADDR="mongodb://db:27017/atsgodb"
      - ATSGO_MASON_PATH=/root/static/images/masonpics/
      - ATSGO_PIERCE_PATH=/root/static/images/piercepics/
      - ATSGO_KITSAP_PATH=/root/static/images/kitsappics/

    networks:
      - atsGo
    ports:
      - 80:80
    depends_on:
      - db
      
networks:
  atsGo:
